### ISSUE TITLE
When generating a new wallet, the NEP2 private key is the only one that displays

### ISSUE THREAD

**Issue by sdixasm** [snowypowers/ansy#2]
When generating a new wallet, the NEP2 private key is the only one that displays.  
I was careful to remember to print my wallet, but it was not obvious that there was a critical blue arrow/button that was needed to display my WIF private key, so I only printed the wallet with a NEP2 key (I did not even know what NEP2 was, so I thought this was just another private key, just like my other wallets.).   Somehow, I lost my password.  In fact, I have a feeling I typed in a random string, thinking I just needed a to provide a unique, random,  locally-generated seed.

So now, in a perfect storm, I have my wallet with only the NEP2 key, no password, and several NEO locked inside. 

The amount is significant.   

Suggested enhancement. 
1. Can you include instructions clearly telling the user that without a password, a NEP2 key is useless? 
2. Let the user know, that if they expect the paper wallet to work like a traditional paper wallet, they will need to click the blue arrow to show and print the WIF key. 

Also -
3. Is there a program you can point me to that will help me crack/brute force the NEP2?   I have the public kay and NEP2 key.  I also have some strings in mind to provide as hints to the cracking utility.   

Please help
I am not a dev.   Just a user.

**Comment by snowypowers** [comment]
1. I havn't seen a case where they ask for a password and then not use your password. 

2. I havn't been maintaining this project much and I do not see it to grow from a UX standpoint.

3. No, I havn't heard of any tool to bruteforce this. A developer can build one probably.

**Comment by bgtoo** [comment]
I just found I did exactly the same - I have a paper wallet printout with only the wallet address and the NEP2 encrypted key, but no trace of the password used to generate it, and no WIF private key. I made it 2 months ago and today tried to load in into the NEON app.

Since I stupidly sent 40 NEO to the wallet, I am VERY keen to get this back - as sdixasm said above, the wallet generation is less than optimum. Plus it's tough on the newbies trying to get into crypto if this sort of thing happens, it puts me off recommending it to anyone who is not a real expert, which is 99.9% of us.

Any way to recover the funds with only the encrypted key and the wallet address? 

It's very frustrating to see the NEO sitting there on the blockchain knowing that me failing to make one click on the ansy page has cost me thousands....

**Comment by snowypowers** [comment]
No one can help you if you forget your password. The best you can do is to try to figure out what would you put into a field labeled `password` and attempt to brute force the password.

Honestly, it doesn't make sense that you will put a password and then print out the WIF as that just renders the password useless (The WIF is not affected by a password).

I do not recommend crypto to anyone who forgets their passwords easily. The entire basis of cryptocurrency is to trust yourself. If you cannot trust yourself to handle your own money, you are better off trusting your money to a bank.

**Comment by bgtoo** [comment]
Yeah thanks...as I'm not the only person to do this, maybe there is an issue with the ergonomics of the wallet generator - all other paper wallets I made (half a dozen or so) just have a print out and QR code of the private key itself. I see where you're coming from with the password to encrypt the key, but this sucks if (like me) there is a moment of inattention.

Like you suggest, I'll get out of crypto, and back to banks where at least the SW is idiot-proof. But it's a pity that you're only catering for the 0.1% - you can forget adoption anytime soon, if this is the attitude.

**Comment by peterwww** [comment]
unfortunately did same mistake and with current Neo prices very expensive one....
